### ISSUE TITLE
Deploy Automático com Travis CI

### ISSUE THREAD

**Issue by GabrielDS** [GDGAracaju/GDGAjuBot#73]
Uma opção que o Travis CI solicita é a automatização no deploy da aplicação. 
Percebi, que o Bot está hospedado no Heroku, o travis tem suporte com o serviço de hospedagem o que facilita na configuração do deploy. 

### Configuração Básica de deploy para Heroku:
```yml
deploy:
  provider: heroku
  api_key: ...
  app: my-app-name-123

```
Além disso, o Travis CI está com uma nova feature que são os Builds Stages. A função das Builds Stages é fazer uma "integração" entre diferentes jobs. Por exemplo, estou a testar minha aplicação em 4 diferentes versões de Python e eu quero que o Travis faça o deploy se, e somente se, os testes derem "Okaay" e os jobs forem relacionados ao merge da Branch Master. Daí, o CI só irá executar o deploy no momento que os testes estiverem concluídos:
 #### Configuração Básica de Build Stages
```yml
jobs:
  include:
    - stage: Deploy Heroku
      if: branch == master
      python: 3.6 
      script: echo "Deploy App to Heroku"
      deploy: &heroku
        provider: heroku
        # ...
```
